#!name=YouTube + Locket + Spotify Premium
#!desc=Gộp module Premium cho YouTube, Locket, Spotify
#!tag=YouTube, Locket, Spotify, Premium
# 💬 Discord: https://discord.gg/juY9tw5AJY

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[Script]
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch))(\?(.*))?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js,argument="{"lyricLang":"{{{歌词翻译语言}}}","captionLang":"{{{字幕翻译语言}}}","blockUpload":{{{屏蔽上传按钮}}},"blockImmersive":{{{屏蔽选段按钮}}},"blockShorts":{{{屏蔽Shorts按钮}}},"debug":{{{启用调试模式}}}}"

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data="" status-code=200

[General]
user-agent = Locket/1.0.0 (iPhone; iOS 26.3; Scale/3.00)

[Script]
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/main/locketfix3.js, requires-body=true, max-size=-1, timeout=120
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/main/header2.js, timeout=120

[Script]
spotify = type=http-response, pattern=^https:\/\/api\.spotify\.com\/v1\/me, script-path=https://raw.githubusercontent.com/NightmarketServer/Spotify/main/spotify.js, requires-body=true, max-size=-1

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com, api.revenuecat.com, raw.githubusercontent.com, api.spotify.com
